server: 
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: "http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/"

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true



resilience4j:
  bulkhead:
    instances:
      bulkheadapi-gateway:
        maxWaitDuration: 2ms
        maxConcurrentCalls: 20
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
    instances:
      api-gateway:
        slidingWindowSize: 2
        failureRateThreshold: 50
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        waitDurationInOpenState: 10000
        event-consumer-buffer-size: 10
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.lang.IllegalStateException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException