server: 
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      ribbon:
        enabled: false

    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      default-filters:
        - name: Retry
          args:
            retries: 5
            methods: GET, POST, PUT, DELETE
            series: SERVER_ERROR
            exceptions: java.io.IOException
            statuses: BAD_GATEWAY
            backoff:
              firstBackoff: 20ms
              maxBackoff: 100ms
              factor: 3
              baseadOnPreviousValue: true
      routes:
        - id: microservices1-route
          uri: lb://MICROSERVICE1-THIRDPARTY-MCP
          predicates:
            - Path=/ms1/**
          filters:
            - StripPrefix=2
        - id: microservices2-route
          uri: lb://MICROSERVICE2-OLLAMA-MCP-INTERNAL
          predicates:
            - Path=/ms2/**
          filters:
            - StripPrefix=2
        - id: microservices3-route
          uri: lb://MICROSERVICE3-SERVERLESS-FUNCTION
          predicates:
            - Path=/ms3**
          filters:
            - StripPrefix=2
    config:
      import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka/,http://localhost:8082/eureka/,http://localhost:8083/eureka/"

management:
  endpoint:
    gateway:  
      enabled: true
    circuit-breakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: ""
    health: 
      circuit-breakers: 
        enabled: true