spring:
  application:
    name: Distributed AI Microservices Spring
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - name: Retry
          args:
            retries: 5
            methods: GET, POST, PUT, DELETE
            statuses: BAD_GATEWAY
            backoff:
              firstBackoff: 20ms
              maxBackoff: 100ms
              factor: 3
              baseadOnPreviousValue: true

server: 
  port: 8080 #?

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: "http://localhost:8081/eureka/,http://localhost:8082/eureka/,http://localhost:8083/eureka/"

management:
  endpoint:
    gateway:  
      enabled: true
    circuit-breakers:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: ""
    health: 
      circuit-breakers: 
        enabled: true