server:
  port: 8083

spring:
  application:
    name: eureka-server-3

  cloud:
    config:
      import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: "http://localhost:8081/eureka/, http://localhost:8082/eureka/"

management:
  endpoint:
    web:
      exposure:
        include: "*"