server:
  port: 8081

spring:
  application:
    name:  eureka-server-1

  cloud:
    config:
      import: "optional:configserver:http://localhost:8888"

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    defaultZone: "http://localhost:8082/eureka/, http://localhost:8083/eureka/"

management:
  endpoint:
    web:
      exposure:
        include: "*"