server:
  port:8082

spring:
  application:
    name: microservice-ai
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
  ai:
    model:
      chat: openai
    openai:
      api-key: ${GEMINI_API_KEY}
      base-url: https://generativelanguage.googleapis.com/v1beta/openai
      chat:
        completions-path: /chat/completions
        options:
          model: gemini-2.0-flash
    mcp:
      client:
        toolcallback:
          enabled: true
        sse:
          connections:
            server:
              url: "http://localhost:8081"
management:
  endpoints:
    web:
      exposure:
        include: prometheus,health,info
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: "http://peer1:8761/eureka/,http://peer2:8762/eureka/,http://peer3:8763/eureka/"