server:
  port:8082

spring:
  application:
    name: microservice-ai

  cloud:
    loadbalancer:
      ribbon:
        enabled: true

ai:
  model:
    chat: openai
  openai:
    api-key: ${GOOGLE_API_KEY}
    base-url: https://generative-language.googleapis.com/v1beta/openai
    chat:
      completions-path: /chat/completions
      options:
        model: gemini-2.0-flash
  mcp:
    client:
      toolcallback:
        enabled: true
      sse:
        connections:
          server:
            url: http://localhost:8081/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}