spring:
  application:
    name: microservices3-serverless-function
  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: "http://localhost:8888"
    request:
      connect-timeout: 5000
      read-timeout: 5000
    fail-fast: true
    retry:
      max-attempts: 6
      initial-interval: 1000
      max-interval: 2000
      multiplier: 1.1

management:
  endpoint:
    health:
      show-details: ALWAYS
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: refresh
    health:
      circuit-breakers:
        enabled: true